x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: ./airflow/Dockerfile
  env_file:
    - .env
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./ingestion:/opt/airflow/ingestion
    - ./dbt:/opt/airflow/dbt
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - weather_network

services:

  postgres:
    image: postgres:16
    container_name: weather_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weather_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather_user -d weather_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  cloudbeaver:
    image: dbeaver/cloudbeaver:24.2.5
    container_name: weather_cloudbeaver
    restart: unless-stopped
    ports:
      - "${CLOUDBEAVER_PORT}:8978"
    depends_on:
      - postgres
    volumes:
      - ./cloudbeaver/connections:/opt/cloudbeaver/conf/connections
      - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace
    networks:
      - weather_network


  ingestion:
    build:
      context: ./ingestion
    container_name: weather_ingestion
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - weather_network


  dbt:
    build:
      context: ./dbt
    container_name: weather_dbt
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - weather_network


  streamlit:
    build:
      context: .
      dockerfile: ./streamlit/Dockerfile
    container_name: weather_streamlit
    env_file:
      - .env
    ports:
      - "${STREAMLIT_PORT}:8501"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./ingestion:/app/ingestion
      - ./dbt:/app/dbt
    networks:
      - weather_network

  dbt-docs:
    build:
      context: ./dbt
    container_name: weather_dbt_docs
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dbt:/dbt
    ports:
      - "${DBT_DOCS_PORT}:8080"
    command:
      >
      sh -c "
      dbt docs generate &&
      dbt docs serve
      --host 0.0.0.0
      --port 8080
      "
    networks:
      - weather_network

  airflow-init:
    <<: *airflow-common
    container_name: weather_airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - >-
        airflow db migrate &&
        (airflow users create
        --username "${AIRFLOW_ADMIN_USERNAME:-admin}"
        --password "${AIRFLOW_ADMIN_PASSWORD:-admin}"
        --firstname Air --lastname Flow --role Admin
        --email admin@example.com || true)

  airflow-webserver:
    <<: *airflow-common
    container_name: weather_airflow_webserver
    command: webserver
    ports:
      - "${AIRFLOW_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: weather_airflow_scheduler
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres_data:

networks:
  weather_network:
    driver: bridge
